language: python

python:
- '3.6'

install:
- pip install -r requirements.txt
- pip install codecov
- pip install pylint==1.8.1

script:
- nosetests --with-coverage --cover-package=src --cover-erase --cover-inclusive
- pylint --disable=W test
- cd src
- pylint --disable=W src
- cd ..

after_success:
- codecov

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
