"""
    Columns related constants
"""

DATE = "Date"
MONTH_DATE = "Month_date"
MONTH = "Month"
YEAR = "Year"
NOTES = "Note"
AMOUNT = "Amount"
CATEGORY = "Category"
TYPE = "Type"

LOG_MODULE = "Module"
LOG_TYPE = "Type"
LOG_DETAILS = "Comments"
LOG_TIME = "Time"
LOG_ERROR_TYPE = "Type Error"
LOG_ERROR_DETAILS = "Details Error"
LOG_ERROR_LINE = "Line error"
